### ISSUE TITLE
Daemon crashes

### ISSUE THREAD

**Issue by ttaylor-st** [0bCdian/Waypaper-Engine#15]
Running `waypaper-engine daemon` gives the following output:
```bash
❯ waypaper-engine daemon;
starting daemon...
```
before the process exits, I also receive a notification, "Daemon crashed, Error: Could not set image,check the logs", but it's unclear *where* the relevant logs would be.

Sorry I don't have all that information for you to go off of. I installed using the `waypaper-engine` and `waypaper-engine-git` AUR packages, both give the same result as described above. 

I'm using Arch Linux, w/ Node v20.12.2

**Comment by 0bCdian** [comment]
Did you have a previous version installed before? I'm gonna go out on a limb and say this may be caused because there was a bug in which I didn't check if a monitor was selected before saving  a playlist in the 2.0.0 version (saving a playlists automatically starts it) so this crash is probably the daemon panicking because the monitor information is empty. I'll change the default behaviour of crashing to just defaulting to set it to all available monitors instead. In the meantime  if you want a more immediate fix , if you know a little sql and have SQLite installed in your system or a db inspector like dbbrowser for SQLite, you could delete all entries from the activePlaylist table to stop crashes and set the playlist with the latest version of the git package, in which this issue was fixed, but this is a bandaid fix, I'll get this done by later today, since crashing the whole app because of this is a bad design decision. I'm sorry for the inconvenience.

**Comment by 0bCdian** [comment]
Thanks! I'm glad you liked it! Btw I'll be closing this issue, I fixed the wrong behavior that caused this error on latest git, and finally added logging, if you run the app with --logs it should create log files on the .waypaper_engine dir in $HOME. If anything else pops up or if you have any feedback feel free to open another issue, take care!
