### ISSUE TITLE
Daemon does not start

### ISSUE THREAD

**Issue by kyoungerman** [0bCdian/Waypaper-Engine#17]
I am using Arch and Wayland, I am using the latest waypaper-engine-git from the AUR. This is fresh install, I haven't been able to use waypaper-engine yet.

Whenever I run the daemon with the command waypaper-engine daemon, it just says "starting daemon..." but the daemon never actually starts.

If I pass the logs flag, it works, but I do not have any logs in ~/.waypaper-engine

when I run waypaper-engine run, I get this:

Error: Failed to establish connection to waypaper daemon.
    at testConnection (/opt/waypaper-engine/resources/app/dist-electron/main.js:13872:9)
    at async initWaypaperDaemon (/opt/waypaper-engine/resources/app/dist-electron/main.js:13849:7)
    at async /opt/waypaper-engine/resources/app/dist-electron/main.js:15174:3
Could not start wpe-daemon, shutting down app...
/usr/bin/waypaper-engine: line 805: Something went wrong: command not found

**Comment by 0bCdian** [comment]
Hi! Yes, this was caused because I didn't include a dependency (the one that logs the files, that's why don't see the logs hahaha) in the daemon's package.json, I had fixed this earlier and thought I pushed the changes but it seems I didn't 😅. Try the latest git and let me know if anything else pops up

**Comment by kyoungerman** [comment]
That worked, thank you! 

I updated to the new git version and now I can launch the app!
