### ISSUE TITLE
Can not delete a picture

### ISSUE THREAD

**Issue by TwelveNight** [0bCdian/Waypaper-Engine#2]
![image](https://github.com/0bCdian/Waypaper-Engine/assets/113519679/3862a623-808f-4920-a495-4331623e7472)

Can not start the GUI frome the tray,When I config the app start from the tray,I can never start the GUI

**Comment by 0bCdian** [comment]
I was able to reproduce this on my machine, I'll notify back when it's fixed!

**Comment by 0bCdian** [comment]
Latest commit fixed the delete problem in the image context menu. This was caused because I naively reused the logic that imageCards in the react front-end have to delete themselves into the main process, thus the window object being undefined and throwing an exception when trying to access the confirm method.
