### ISSUE TITLE
This wallpaper utility is almost perfect

### ISSUE THREAD

**Issue by Ein420** [0bCdian/Waypaper-Engine#9]
I just wish there was a way to scale the app better, the ui is quite huge and the whole window needs to be stretched just to see the bottom blue buttons

**Comment by 0bCdian** [comment]
Hi! I'm currently doing a heavy rewrite of the app since almost a month ago (Adding a playlist system per monitor instead of current one which just clones images across all monitors) and I'm tweaking the css to make the app more responsive. Expect these changes to come soon when I release 2.0 which shouldn't take me more than a few weeks.

**Comment by 0bCdian** [comment]
Hi! i wanted to let you know how things are going, here I showcase the progress being made!

https://github.com/0bCdian/Waypaper-Engine/issues/7#issuecomment-2050289649

**Comment by 0bCdian** [comment]
Btw the issue about the scripts not being executed in playlists has been fixed already, I still have to polish the css to make the app more responsive , but we're getting there! :)

**Comment by 0bCdian** [comment]
Hi! I released a new version which improves the usability on smaller sizes, try out and if anything pops up ,feel free to open another issue!
